

### Kullanici kaydet (token döner, otomatik login)
POST http://localhost:5021/api/auth/register
Content-Type: application/json

{
  "Username": "cihan",
  "Password": "sbb123",
  "Role": "Admin"
}

> {% client.global.set("token", response.body.token) %}

### Giris yap (token al)
POST http://localhost:5021/api/auth/login
Content-Type: application/json

{
  "Username": "cihan",
  "Password": "sbb123"
}

> {% client.global.set("token", response.body.token) %}

### Authorize gerektiren endpoint (token olmadan - 401 gelmeli)
GET http://localhost:5021/api/kitap

### Authorize gerektiren endpoint (token ile - 200 gelmeli)
GET http://localhost:5021/api/kitap
Authorization: Bearer {{token}}

### Kitap ekle (token ile)
POST http://localhost:5021/api/kitap
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Title": "Lotr",
  "YazarId": 1
}

###
### --- URUN ---

### Tüm ürünleri getir
GET http://localhost:5021/api/urun

### Ürün ekle
POST http://localhost:5021/api/urun
Content-Type: application/json

{
  "Ad": "Android",
  "Fiyat": 125000,
  "StokAdedi": 10,
  "kategoriId": 1
}

### ID ile getir
GET http://localhost:5021/api/urun/1

###
### --- KATEGORI ---

GET http://localhost:5021/api/category

###
### --- YAZAR ---

### Yazarlari getir
GET http://localhost:5021/api/yazar

### Yazar ekle
POST http://localhost:5021/api/yazar
Content-Type: application/json

{
  "Ad": "Cihan",
  "Soyad": "BAS"
}

###
### --- KITAP ---

### Tum kitaplari getir
GET http://localhost:5021/api/kitap

### Sifre sifirlama
GET http://localhost:5021/api/auth/profile
